<?php
/**
 * Created by PhpStorm.
 * User: brunosalzano
 * Date: 26/07/16
 * Time: 05:49
 */
namespace isrba\metronic\bundles;

use yii\web\AssetBundle;
use isrba\metronic\Metronic;

class BaseAssetBundle extends AssetBundle {
    public function init()
    {
        if (Metronic::getComponent())
        {
            $this->basePath = Metronic::getComponent()->basePath;
            $this->baseUrl = Metronic::getComponent()->baseUrl;
        }

        if (YII_ENV != 'dev') {
            foreach($this->css as $k => $v) {
                if (strpos($v,'.min.css') === false) {
                    $fileName = str_replace('.css','.min.css', $v);
                    $newFile = \Yii::getAlias($this->basePath) . '/' . $fileName;
                    if (!file_exists($newFile)) {
                        $fileName = $v;
                    }
                    $this->css[$k] = $fileName;
                }
            }
            foreach($this->js as $k => $v) {
                if (strpos($v,'.min.js') === false) {
                    $fileName = str_replace('.js','.min.js', $v);
                    $newFile = \Yii::getAlias($this->basePath) . '/' . $fileName;
                    if (!file_exists($newFile)) {
                        $fileName = $v;
                    }
                    $this->js[$k] = $fileName;
                }
            }
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}